package com.gamesplanet.tv;
import android.Manifest;import android.app.*;import android.content.*;import android.content.pm.*;import android.database.Cursor;import android.graphics.*;import android.graphics.drawable.*;import android.media.MediaPlayer;import android.net.Uri;import android.os.*;import android.provider.*;import android.view.*;import android.widget.*;
import org.json.*;import org.w3c.dom.*;import javax.xml.parsers.*;import java.io.*;import java.util.*;import java.util.concurrent.*;import java.util.zip.*;
public class MainActivity extends Activity {
 final ExecutorService worker=Executors.newSingleThreadExecutor(); Handler ui=new Handler(Looper.getMainLooper());
 android.content.SharedPreferences prefs; FrameLayout root; ListView list; TextView status; ImageView preview; TextureView texture; MediaPlayer player;File themesDir,workspace,currentTheme; JSONArray catalog=new JSONArray(); ArrayList<JSONObject> visible=new ArrayList<>(); String selectedSystem="All"; ProgressDialog progress; long downloadId=-1; String pendingAction=""; float lx=.636f,ly=.185f,lw=.30f,lh=.63f; String selector="#9B3F0D";
 final String[] PACKAGES={"com.retroarch","com.retroarch.aarch64","com.retroarch.ra32"};
 final String APKURL="https://buildbot.libretro.com/stable/1.22.2/android/RetroArch.apk";
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setFlags(1024,1024);prefs=getSharedPreferences("gp",0);themesDir=new File(getFilesDir(),"themes");themesDir.mkdirs();workspace=new File(Environment.getExternalStorageDirectory(),"GamesPlanetTV");
  try{for(String t:new String[]{"kratos","scorpion"})assetTree("themes/"+t,new File(themesDir,t));File c=new File(getFilesDir(),"catalog.json");if(c.exists())catalog=new JSONArray(read(c));}catch(Exception e){message("Library",e.toString());}
  currentTheme=new File(themesDir,prefs.getString("theme","kratos"));draw();
  IntentFilter f=new IntentFilter(DownloadManager.ACTION_DOWNLOAD_COMPLETE);if(Build.VERSION.SDK_INT>=33)registerReceiver(downloadReceiver,f,Context.RECEIVER_EXPORTED);else registerReceiver(downloadReceiver,f);
 }
 void assetTree(String key,File dst)throws IOException{String[] children=getAssets().list(key);if(children!=null&&children.length>0){dst.mkdirs();for(String c:children)assetTree(key+"/"+c,new File(dst,c));}else if(!dst.exists()){dst.getParentFile().mkdirs();try(InputStream in=getAssets().open(key);OutputStream out=new FileOutputStream(dst)){pipe(in,out,512L*1024*1024);}}}
 static String read(File f)throws IOException{try(InputStream in=new FileInputStream(f);ByteArrayOutputStream o=new ByteArrayOutputStream()){pipe(in,o,16*1024*1024);return o.toString("UTF-8");}}
 static long pipe(InputStream in,OutputStream out,long limit)throws IOException{byte[] buf=new byte[65536];long total=0;int n;while((n=in.read(buf))!=-1){total+=n;if(total>limit)throw new IOException("File too large");out.write(buf,0,n);}return total;}
 void write(File f,String data)throws IOException{f.getParentFile().mkdirs();try(OutputStream o=new FileOutputStream(f)){o.write(data.getBytes("UTF-8"));}}
 void message(String title,String body){new AlertDialog.Builder(this).setTitle(title).setMessage(body).setPositiveButton("OK",null).show();}
 void async(String title,Job job){progress=new ProgressDialog(this);progress.setTitle(title);progress.setMessage("Please wait…");progress.setCancelable(false);progress.show();worker.execute(()->{String error=null;try{job.run();}catch(Exception e){error=e.getMessage()==null?e.toString():e.getMessage();}final String err=error;ui.post(()->{if(isFinishing())return;if(progress!=null)progress.dismiss();if(err!=null)message(title,err);draw();});});}
 interface Job{void run()throws Exception;}
 void parseTheme(){lx=.636f;ly=.185f;lw=.30f;lh=.63f;selector="#9B3F0D";try{
  File xml=new File(currentTheme,"theme.xml");if(!xml.exists())return;DocumentBuilderFactory f=DocumentBuilderFactory.newInstance();try{f.setFeature("http://apache.org/xml/features/disallow-doctype-decl",true);}catch(Exception ignored){}f.setExpandEntityReferences(false);Document d=f.newDocumentBuilder().parse(xml);NodeList ls=d.getElementsByTagName("textlist");for(int i=0;i<ls.getLength();i++){Element e=(Element)ls.item(i);if(!"gamelist".equals(e.getAttribute("name")))continue;String[]pos=value(e,"pos").trim().split("\\s+"),size=value(e,"size").trim().split("\\s+");float x=Float.parseFloat(pos[0]),y=Float.parseFloat(pos[1]),w=Float.parseFloat(size[0]),h=Float.parseFloat(size[1]);if(x>=0&&y>=0&&w>.1&&h>.1&&x+w<=1.01&&y+h<=1.01){lx=x;ly=y;lw=w;lh=h;}String col=value(e,"selectorColor");if(col.length()>=6)selector="#"+col.substring(0,6);break;}
 }catch(Exception ignored){}}
 String value(Element e,String tag){NodeList n=e.getElementsByTagName(tag);return n.getLength()>0?n.item(0).getTextContent():"";}
 File media(String tag,String name,String fallback){try{DocumentBuilderFactory f=DocumentBuilderFactory.newInstance();try{f.setFeature("http://apache.org/xml/features/disallow-doctype-decl",true);}catch(Exception ignored){}Document d=f.newDocumentBuilder().parse(new File(currentTheme,"theme.xml"));NodeList nodes=d.getElementsByTagName(tag);for(int i=0;i<nodes.getLength();i++){Element e=(Element)nodes.item(i);if(!e.getAttribute("name").contains(name))continue;String p=value(e,"path").replace("./","");File file=Rules.child(currentTheme,p);if(file.isFile())return file;}}catch(Exception ignored){}return new File(currentTheme,fallback);}
 void draw(){if(isFinishing())return;releaseVideo();parseTheme();root=new FrameLayout(this);root.setBackgroundColor(Color.BLACK);setContentView(root);
  ImageView bg=new ImageView(this);File art=media("image","background","assets/background.jpg");if(art.exists())bg.setImageBitmap(BitmapFactory.decodeFile(art.getPath()));bg.setScaleType(ImageView.ScaleType.FIT_XY);root.addView(bg,new FrameLayout.LayoutParams(-1,-1));
  texture=new TextureView(this);root.addView(texture,new FrameLayout.LayoutParams(-1,-1));texture.setSurfaceTextureListener(new TextureView.SurfaceTextureListener(){public void onSurfaceTextureAvailable(SurfaceTexture s,int w,int h){playVideo(s);}public void onSurfaceTextureSizeChanged(SurfaceTexture s,int w,int h){}public boolean onSurfaceTextureDestroyed(SurfaceTexture s){releaseVideo();return true;}public void onSurfaceTextureUpdated(SurfaceTexture s){}});
  preview=new ImageView(this);preview.setScaleType(ImageView.ScaleType.FIT_CENTER);try{preview.setImageBitmap(BitmapFactory.decodeStream(getAssets().open("loading.png")));}catch(Exception ignored){}root.addView(preview);list=new ListView(this);list.setChoiceMode(ListView.CHOICE_MODE_SINGLE);list.setSelector(new ColorDrawable(Color.parseColor(selector)));list.setDivider(new ColorDrawable(0x223f2618));list.setDividerHeight(1);list.setBackgroundColor(0x98060a11);list.setOnItemClickListener((a,v,p,id)->play(visible.get(p)));list.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener(){public void onNothingSelected(AdapterView<?>p){}public void onItemSelected(AdapterView<?>p,View v,int n,long id){if(n<visible.size())showCover(visible.get(n));}});list.setOnItemLongClickListener((a,v,p,id)->{gameOptions(visible.get(p));return true;});root.addView(list);
  LinearLayout toolbar=new LinearLayout(this);toolbar.setOrientation(LinearLayout.HORIZONTAL);toolbar.setGravity(Gravity.CENTER);toolbar.setBackgroundColor(0xdc090c14);root.addView(toolbar);
  button(toolbar,"USB Games",()->pick(101));button(toolbar,"Systems",this::systems);button(toolbar,"Themes",this::themeMenu);button(toolbar,"BIOS",()->{if(storage("bios"))pick(102);});button(toolbar,"Setup",this::setup);button(toolbar,"Exit",()->finish());
  status=new TextView(this);status.setTextColor(Color.WHITE);status.setTextSize(12);status.setGravity(Gravity.CENTER);status.setBackgroundColor(0xb0000000);root.addView(status);updateList();
  root.post(()->{int w=root.getWidth(),h=root.getHeight();position(preview,(int)(.29*w),(int)(.285*h),(int)(.26*w),(int)(.20*h));position(list,(int)(lx*w),(int)(ly*h),(int)(lw*w),(int)(lh*h));position(toolbar,0,(int)(h*.92),w,(int)(h*.08));position(status,(int)(lx*w),(int)(h*.84),(int)(lw*w),(int)(h*.055));if(!visible.isEmpty())list.requestFocus();});
 }
 void position(View v,int x,int y,int w,int h){FrameLayout.LayoutParams p=new FrameLayout.LayoutParams(w,h);p.leftMargin=x;p.topMargin=y;v.setLayoutParams(p);}
 void button(LinearLayout row,String text,Runnable action){Button b=new Button(this);b.setText(text);b.setTextSize(12);b.setAllCaps(false);b.setTextColor(Color.WHITE);GradientDrawable normal=new GradientDrawable();normal.setColor(0xb0152030);normal.setStroke(1,0xffae7936);StateListDrawable states=new StateListDrawable();GradientDrawable focus=new GradientDrawable();focus.setColor(0xff88401b);states.addState(new int[]{android.R.attr.state_focused},focus);states.addState(new int[]{android.R.attr.state_pressed},focus);states.addState(new int[]{},normal);b.setBackground(states);b.setOnClickListener(v->action.run());row.addView(b,new LinearLayout.LayoutParams(0,-1,1));}
 void updateList(){visible.clear();for(int i=0;i<catalog.length();i++){JSONObject j=catalog.optJSONObject(i);if(j!=null&&(selectedSystem.equals("All")||selectedSystem.equals(j.optString("system"))))visible.add(j);}list.setAdapter(new BaseAdapter(){public int getCount(){return visible.size();}public Object getItem(int p){return visible.get(p);}public long getItemId(int p){return p;}public View getView(int p,View recycled,android.view.ViewGroup parent){TextView t=recycled instanceof TextView?(TextView)recycled:new TextView(MainActivity.this);t.setText(visible.get(p).optString("title"));t.setTextSize(18);try{File font=new File(currentTheme,"assets/font.ttf");if(font.isFile())t.setTypeface(Typeface.createFromFile(font));}catch(Exception ignored){}t.setSingleLine(true);t.setEllipsize(android.text.TextUtils.TruncateAt.END);t.setPadding(14,12,8,12);t.setTextColor(Color.WHITE);return t;}});status.setText(visible.isEmpty()?"USB Games → choose roms folder":selectedSystem+" • "+visible.size()+" games • OK: Play • Hold OK: Core");}
 
 HashMap<String,String> coverMap(Uri tree,String parent,ArrayList<Row>rows){HashMap<String,String>map=new HashMap<>();for(Row row:rows)if(row.name.equalsIgnoreCase("gamelist.xml")){try(InputStream in=getContentResolver().openInputStream(DocumentsContract.buildDocumentUriUsingTree(tree,row.id))){DocumentBuilderFactory f=DocumentBuilderFactory.newInstance();try{f.setFeature("http://apache.org/xml/features/disallow-doctype-decl",true);}catch(Exception ignored){}Document d=f.newDocumentBuilder().parse(in);NodeList games=d.getElementsByTagName("game");for(int i=0;i<games.getLength();i++){Element g=(Element)games.item(i);String path=value(g,"path");String image=value(g,"image");if(image.isEmpty())image=value(g,"thumbnail");if(!image.isEmpty())map.put(new File(path).getName(),image.startsWith("./")?image.substring(2):image);}}catch(Exception ignored){}}return map;}
 String selectedCover="";
 void showCover(JSONObject game){String cover=game.optString("cover"),key=game.optString("path")+game.optString("uri");selectedCover=key;if(cover.isEmpty()){try{preview.setImageBitmap(BitmapFactory.decodeStream(getAssets().open("loading.png")));}catch(Exception ignored){}return;}worker.execute(()->{Bitmap bitmap=null;try{Uri tree=Uri.parse(game.getString("tree"));String id=find(tree,game.getString("parent"),Rules.safeRelative(cover));Uri u=DocumentsContract.buildDocumentUriUsingTree(tree,id);BitmapFactory.Options opt=new BitmapFactory.Options();opt.inSampleSize=2;try(InputStream in=getContentResolver().openInputStream(u)){bitmap=BitmapFactory.decodeStream(in,null,opt);}}catch(Exception ignored){}final Bitmap image=bitmap;ui.post(()->{if(selectedCover.equals(key)&&image!=null&&preview!=null)preview.setImageBitmap(image);});});}

 void systems(){TreeSet<String>s=new TreeSet<>();s.add("All");for(int i=0;i<catalog.length();i++)s.add(catalog.optJSONObject(i).optString("system"));String[]a=s.toArray(new String[0]);new AlertDialog.Builder(this).setTitle("Systems").setItems(a,(d,n)->{selectedSystem=a[n];updateList();}).show();}
 void playVideo(SurfaceTexture s){releaseVideo();File file=media("video","background","assets/live-background.mp4");if(!file.exists()){texture.setVisibility(View.GONE);return;}try{player=new MediaPlayer();player.setDataSource(file.getAbsolutePath());Surface surface=new Surface(s);player.setSurface(surface);surface.release();player.setVolume(0,0);player.setLooping(true);player.setOnPreparedListener(p->p.start());player.setOnErrorListener((p,w,e)->{releaseVideo();texture.setVisibility(View.GONE);return true;});player.prepareAsync();}catch(Exception e){releaseVideo();texture.setVisibility(View.GONE);}}
 void releaseVideo(){if(player!=null){try{player.release();}catch(Exception ignored){}player=null;}}
 @Override public void onPause(){releaseVideo();super.onPause();}
 @Override public void onResume(){super.onResume();if(texture!=null&&texture.isAvailable())playVideo(texture.getSurfaceTexture());}
 @Override public void onDestroy(){try{unregisterReceiver(downloadReceiver);}catch(Exception ignored){}releaseVideo();worker.shutdown();super.onDestroy();}
 @Override public void onBackPressed(){new AlertDialog.Builder(this).setTitle("Close Games Planet?").setPositiveButton("Exit",(d,n)->finish()).setNegativeButton("Keep playing",null).show();}
 void pick(int code){try{Intent i=new Intent(code==103?Intent.ACTION_OPEN_DOCUMENT:Intent.ACTION_OPEN_DOCUMENT_TREE);if(code==103){i.setType("application/zip");i.addCategory(Intent.CATEGORY_OPENABLE);}i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION);startActivityForResult(i,code);}catch(Exception e){message("USB picker","This TV has no file picker. Use Setup → Storage permission, then Manual folder path.");}}
 @Override public void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(result!=RESULT_OK||data==null||data.getData()==null)return;Uri u=data.getData();try{getContentResolver().takePersistableUriPermission(u,Intent.FLAG_GRANT_READ_URI_PERMISSION);}catch(Exception ignored){}
  if(request==101){prefs.edit().putString("tree",u.toString()).apply();async("Scanning USB",()->{JSONArray fresh=new JSONArray();scan(u,DocumentsContract.getTreeDocumentId(u),"",fresh,0);catalog=fresh;write(new File(getFilesDir(),"catalog.json"),catalog.toString());});}
  else if(request==102)async("Importing BIOS",()->{workspace.mkdirs();copyTree(u,DocumentsContract.getTreeDocumentId(u),new File(workspace,"bios"),0,new long[]{0});prefs.edit().putString("bios",new File(workspace,"bios").getAbsolutePath()).apply();});
  else if(request==103)async("Importing themes",()->importZip(u));
 }
 void scan(Uri tree,String id,String folder,JSONArray arr,int depth)throws Exception{if(depth>20||arr.length()>50000)throw new IOException("Library too large; choose a smaller ROM folder.");ArrayList<Row> rows=children(tree,id);HashMap<String,String> covers=coverMap(tree,id,rows);HashSet<String>tracks=new HashSet<>();for(Row r:rows)if(r.name.toLowerCase().endsWith(".cue")){try(InputStream in=getContentResolver().openInputStream(DocumentsContract.buildDocumentUriUsingTree(tree,r.id));ByteArrayOutputStream bytes=new ByteArrayOutputStream()){pipe(in,bytes,1024*1024);java.util.regex.Matcher m=java.util.regex.Pattern.compile("(?im)^\\s*FILE\\s+(?:\"([^\"]+)\"|(\\S+))").matcher(bytes.toString("UTF-8"));while(m.find()){String ref=m.group(1)!=null?m.group(1):m.group(2);tracks.add(new File(ref).getName().toLowerCase());}}catch(Exception ignored){}}
  for(Row r:rows){String rel=folder.isEmpty()?r.name:folder+"/"+r.name;if(r.directory){String low=r.name.toLowerCase();if(!Arrays.asList("bios","system","images","videos","media","themes","saves","states").contains(low)&&!low.startsWith("."))scan(tree,r.id,rel,arr,depth+1);}else{if(tracks.contains(r.name.toLowerCase()))continue;String sys=Rules.system(folder,r.name);if(sys.isEmpty())continue;JSONObject game=new JSONObject();Uri uri=DocumentsContract.buildDocumentUriUsingTree(tree,r.id);game.put("cover",covers.containsKey(r.name)?covers.get(r.name):"");game.put("title",r.name.replaceFirst("\\.[^.]+$",""));game.put("system",sys);game.put("name",r.name);game.put("uri",uri.toString());game.put("tree",tree.toString());game.put("id",r.id);game.put("parent",id);game.put("relative",rel);game.put("path",realPath(r.id));if(arr.length()>=50000)throw new IOException("Choose a smaller ROM folder (maximum 50000 games).");arr.put(game);}}
 }
 static class Row {String id,name;boolean directory;Row(String i,String n,boolean d){id=i;name=n;directory=d;}}
 ArrayList<Row> children(Uri tree,String id)throws Exception{ArrayList<Row> result=new ArrayList<>();Uri uri=DocumentsContract.buildChildDocumentsUriUsingTree(tree,id);try(Cursor c=getContentResolver().query(uri,new String[]{DocumentsContract.Document.COLUMN_DOCUMENT_ID,DocumentsContract.Document.COLUMN_DISPLAY_NAME,DocumentsContract.Document.COLUMN_MIME_TYPE},null,null,null)){if(c==null)throw new IOException("USB not available; reconnect and select its folder.");while(c.moveToNext())result.add(new Row(c.getString(0),c.getString(1),DocumentsContract.Document.MIME_TYPE_DIR.equals(c.getString(2))));}result.sort((a,b)->a.name.compareToIgnoreCase(b.name));return result;}
 String realPath(String id){int i=id.indexOf(':');if(i<0)return "";String volume=id.substring(0,i),tail=id.substring(i+1);if(tail.contains(".."))return "";File root=volume.equalsIgnoreCase("primary")?Environment.getExternalStorageDirectory():new File("/storage",volume);return new File(root,tail).getAbsolutePath();}
 boolean storage(String next){if(Build.VERSION.SDK_INT>=30&&Environment.isExternalStorageManager())return true;if(Build.VERSION.SDK_INT>=23&&checkSelfPermission(Manifest.permission.WRITE_EXTERNAL_STORAGE)!=PackageManager.PERMISSION_GRANTED){pendingAction=next;requestPermissions(new String[]{Manifest.permission.READ_EXTERNAL_STORAGE,Manifest.permission.WRITE_EXTERNAL_STORAGE},100);return false;}return true;}
 @Override public void onRequestPermissionsResult(int r,String[]p,int[]g){super.onRequestPermissionsResult(r,p,g);boolean granted=g.length>0&&g[0]==PackageManager.PERMISSION_GRANTED;if(granted&&pendingAction.equals("bios"))pick(102);else if(!granted)message("Storage","Allow storage access in Setup → Storage permission. Games stay on your USB; no files were deleted.");pendingAction="";}
 String runtime(){String preferred=prefs.getString("runtime","");if(!preferred.isEmpty()&&installed(preferred))return preferred;for(String p:PACKAGES)if(installed(p))return p;return "";}
 boolean installed(String p){try{getPackageManager().getApplicationInfo(p,0);return true;}catch(Exception e){return false;}}
 void play(JSONObject game){String pkg=runtime();if(pkg.isEmpty()){new AlertDialog.Builder(this).setTitle("Install RetroArch once").setMessage("Games Planet is your themed game menu. RetroArch runs the games. Install it, open it once and download the cores for your systems.").setPositiveButton("Install",(d,n)->download()).setNegativeButton("Cancel",null).show();return;}if(!storage("play"))return;
  async("Preparing "+game.optString("title"),()->{String path=game.optString("path");if(path.isEmpty()||!new File(path).canRead())path=stage(game);String sys=game.optString("system"),core=prefs.getString("core_"+sys,Rules.core(sys));String folder=prefs.getString("cores","");if(folder.isEmpty())folder=getPackageManager().getApplicationInfo(pkg,0).dataDir+"/cores";String corePath=folder+"/"+core+(core.endsWith(".so")?"":"_libretro_android.so");File config=config();Intent launch=new Intent(Intent.ACTION_MAIN);launch.setComponent(new ComponentName(pkg,"com.retroarch.browser.retroactivity.RetroActivityFuture"));launch.putExtra("ROM",path);launch.putExtra("LIBRETRO",corePath);launch.putExtra("CONFIGFILE",config.getAbsolutePath());launch.putExtra("QUITFOCUS","true");launch.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP);final String details="ROM: "+path+"\nCore: "+corePath+"\nRuntime: "+pkg;write(new File(getFilesDir(),"last-launch.txt"),details);ui.post(()->{try{startActivity(launch);}catch(Exception e){message("Cannot launch",e.getMessage()+"\nOpen RetroArch once from Setup.");}});});
 }
 String stage(JSONObject game)throws Exception{File root=new File(workspace,"roms");File file=Rules.child(root,game.optString("relative"));if(!file.exists()){file.getParentFile().mkdirs();File tmp=new File(file.getPath()+".part");try(InputStream in=getContentResolver().openInputStream(Uri.parse(game.getString("uri")));OutputStream o=new FileOutputStream(tmp)){if(in==null)throw new IOException("Cannot read game");pipe(in,o,8L*1024*1024*1024);}catch(Exception e){tmp.delete();throw e;}if(!tmp.renameTo(file))throw new IOException("Could not save USB game copy");}
  if(file.getName().toLowerCase().endsWith(".cue")){String cue=read(file);java.util.regex.Matcher m=java.util.regex.Pattern.compile("(?im)^\\s*FILE\\s+(?:\"([^\"]+)\"|(\\S+))").matcher(cue);while(m.find()){String ref=m.group(1)!=null?m.group(1):m.group(2);File dst=Rules.child(file.getParentFile(),ref);if(dst.exists())continue;Uri tree=Uri.parse(game.getString("tree"));String id=find(tree,game.getString("parent"),Rules.safeRelative(ref));dst.getParentFile().mkdirs();File trackTmp=new File(dst.getPath()+".part");try(InputStream in=getContentResolver().openInputStream(DocumentsContract.buildDocumentUriUsingTree(tree,id));OutputStream o=new FileOutputStream(trackTmp)){if(in==null)throw new IOException("Missing CUE track: "+ref);pipe(in,o,8L*1024*1024*1024);}catch(Exception e){trackTmp.delete();throw e;}if(!trackTmp.renameTo(dst))throw new IOException("Could not save CUE track: "+ref);}}
  return file.getAbsolutePath();
 }
 String find(Uri tree,String parent,String rel)throws Exception{String id=parent;for(String p:rel.split("/")){boolean match=false;for(Row r:children(tree,id))if(r.name.equalsIgnoreCase(p)){id=r.id;match=true;break;}if(!match)throw new IOException("Missing companion file: "+rel);}return id;}
 void copyTree(Uri tree,String id,File dir,int depth,long[]total)throws Exception{if(depth>20)throw new IOException("Folder nesting too deep");dir.mkdirs();for(Row r:children(tree,id)){File dst=Rules.child(dir,r.name);if(r.directory)copyTree(tree,r.id,dst,depth+1,total);else{File temp=new File(dst.getPath()+".part");try(InputStream in=getContentResolver().openInputStream(DocumentsContract.buildDocumentUriUsingTree(tree,r.id));OutputStream o=new FileOutputStream(temp)){if(in==null)throw new IOException("Cannot read "+r.name);total[0]+=pipe(in,o,512L*1024*1024);if(total[0]>2L*1024*1024*1024)throw new IOException("BIOS folder exceeds 2 GB; choose only BIOS files.");}catch(Exception e){temp.delete();throw e;}if(!temp.renameTo(dst))throw new IOException("Could not save BIOS "+r.name);}}}
 File config()throws IOException{new File(workspace,"bios").mkdirs();new File(workspace,"saves").mkdirs();new File(workspace,"states").mkdirs();String bios=prefs.getString("bios",new File(workspace,"bios").getPath());File cfg=new File(workspace,"launcher.cfg");write(cfg,"system_directory = \""+bios+"\"\nsavefile_directory = \""+new File(workspace,"saves")+"\"\nsavestate_directory = \""+new File(workspace,"states")+"\"\ninput_autodetect_enable = \"true\"\ninput_overlay_enable = \"false\"\nvideo_fullscreen = \"true\"\nconfig_save_on_exit = \"false\"\nmenu_driver = \"xmb\"\n");return cfg;}
 void gameOptions(JSONObject g){String sys=g.optString("system");String[] c=sys.equals("PS1")?new String[]{"pcsx_rearmed","swanstation","beetle_psx","pcsx_rearmed_neon"}:sys.equals("Arcade")||sys.equals("FBNeo")?new String[]{"mame2010","mame2003_plus","fbneo","mame"}:new String[]{Rules.core(sys)};new AlertDialog.Builder(this).setTitle(sys+" core (download in RetroArch first)").setItems(c,(d,n)->prefs.edit().putString("core_"+sys,c[n]).apply()).setNeutralButton("Custom core",(d,n)->edit("Core filename (without suffix)","core_"+sys,Rules.core(sys))).show();}
 void themeMenu(){ArrayList<File> ts=new ArrayList<>();discover(themesDir,ts,0);String[] names=new String[ts.size()+1];for(int i=0;i<ts.size();i++)names[i]=ts.get(i).getName();names[ts.size()]="+ Import theme ZIP";new AlertDialog.Builder(this).setTitle("Live Themes").setItems(names,(d,n)->{if(n==ts.size())pick(103);else{currentTheme=ts.get(n);String rel=themesDir.toURI().relativize(currentTheme.toURI()).getPath();prefs.edit().putString("theme",rel).apply();draw();}}).show();}
 void discover(File p,ArrayList<File>out,int depth){if(depth>8)return;if(new File(p,"theme.xml").isFile()){out.add(p);return;}File[] children=p.listFiles();if(children!=null)for(File c:children)if(c.isDirectory())discover(c,out,depth+1);}
 void importZip(Uri uri)throws Exception{File dest=new File(themesDir,"import-"+System.currentTimeMillis());dest.mkdirs();boolean ok=false;try(InputStream in=getContentResolver().openInputStream(uri);ZipInputStream zip=new ZipInputStream(in)){ZipEntry e;int entries=0;long total=0;while((e=zip.getNextEntry())!=null){if(++entries>4000)throw new IOException("Theme ZIP has too many files");File f=Rules.child(dest,e.getName());if(e.isDirectory())f.mkdirs();else{f.getParentFile().mkdirs();try(OutputStream o=new FileOutputStream(f)){total+=pipe(zip,o,256L*1024*1024);}if(total>512L*1024*1024)throw new IOException("Theme ZIP too large");}zip.closeEntry();}ArrayList<File> themes=new ArrayList<>();discover(dest,themes,0);if(themes.isEmpty())throw new IOException("No theme.xml found. Import a Batocera theme ZIP.");ok=true;}finally{if(!ok)erase(dest);}}
 void erase(File f){File[]c=f.listFiles();if(c!=null)for(File p:c)erase(p);f.delete();}
 void setup(){String[]items={"Install RetroArch","Open RetroArch / Download cores","USB / storage permission","Rescan saved USB folder","Manual ROM folder path","RetroArch core directory","Choose RetroArch version","Last game launch details","Clear game list (keeps ROMs)","Setup instructions"};new AlertDialog.Builder(this).setTitle("Games Planet setup").setItems(items,(d,n)->{switch(n){case 0:download();break;case 1:openRuntime();break;case 2:permissions();break;case 3:String t=prefs.getString("tree","");if(t.isEmpty())pick(101);else async("Scanning USB",()->{JSONArray a=new JSONArray();Uri u=Uri.parse(t);scan(u,DocumentsContract.getTreeDocumentId(u),"",a,0);catalog=a;write(new File(getFilesDir(),"catalog.json"),a.toString());});break;case 4:manual();break;case 5:edit("Cores folder shown in RetroArch Settings → Directory","cores","");break;case 6:new AlertDialog.Builder(this).setTitle("Installed RetroArch version").setItems(PACKAGES,(dd,x)->prefs.edit().putString("runtime",PACKAGES[x]).apply()).show();break;case 7:try{message("Last launch",read(new File(getFilesDir(),"last-launch.txt")));}catch(Exception e){message("Last launch","No game launched yet");}break;case 8:catalog=new JSONArray();try{write(new File(getFilesDir(),"catalog.json"),"[]");}catch(Exception ignored){}updateList();break;case 9:message("First setup","1. Install/open RetroArch and allow storage.\n2. Online Updater → Core Downloader: install cores (PS1: PCSX ReARMed; Arcade: MAME 2010 matching your ROM set).\n3. Return here → USB Games → choose roms.\n4. BIOS → choose your BIOS folder, if needed.\n5. Select game, press OK.\nHold OK to choose a different core.\nBatocera themes import as backgrounds/live video and game-list layout; advanced XML widgets are not supported.\nGames/BIOS are not bundled. USB direct paths are used when readable; otherwise the selected game and CUE tracks are copied into GamesPlanetTV/roms.\nExit RetroArch to return to this menu.");break;}}).show();}
 void edit(String title,String key,String def){EditText text=new EditText(this);text.setSingleLine(true);text.setText(prefs.getString(key,def));new AlertDialog.Builder(this).setTitle(title).setView(text).setPositiveButton("Save",(d,n)->prefs.edit().putString(key,text.getText().toString().trim()).apply()).setNegativeButton("Cancel",null).show();}
 void manual(){if(!storage("manual"))return;EditText text=new EditText(this);text.setSingleLine(true);text.setHint("/storage/USB-ID/roms");new AlertDialog.Builder(this).setTitle("ROM folder path").setView(text).setPositiveButton("Scan",(d,n)->async("Scanning folder",()->{File f=new File(text.getText().toString().trim());if(!f.isDirectory()||!f.canRead())throw new IOException("Folder not readable. Allow storage permission or use USB picker.");JSONArray a=new JSONArray();scanFile(f,"",a,0);catalog=a;write(new File(getFilesDir(),"catalog.json"),a.toString());})).setNegativeButton("Cancel",null).show();}
 void scanFile(File dir,String rel,JSONArray a,int depth)throws Exception{if(depth>20||a.length()>50000)throw new IOException("Library too large");File[] fs=dir.listFiles();if(fs==null)throw new IOException("Cannot read "+dir);Arrays.sort(fs,(x,y)->x.getName().compareToIgnoreCase(y.getName()));boolean cue=false;for(File f:fs)if(f.getName().toLowerCase().endsWith(".cue"))cue=true;for(File f:fs){String n=f.getName(),relative=rel.isEmpty()?n:rel+"/"+n;if(f.isDirectory()){if(!n.startsWith(".")&&!Arrays.asList("bios","themes","saves","media","images","videos").contains(n.toLowerCase()))scanFile(f,relative,a,depth+1);}else{if(cue&&n.toLowerCase().endsWith(".bin"))continue;String sys=Rules.system(rel,n);if(sys.isEmpty())continue;JSONObject j=new JSONObject();j.put("title",n.replaceFirst("\\.[^.]+$",""));j.put("system",sys);j.put("path",f.getAbsolutePath());j.put("name",n);j.put("relative",relative);a.put(j);}}}
 void permissions(){if(Build.VERSION.SDK_INT>=30){try{startActivity(new Intent("android.settings.MANAGE_APP_ALL_FILES_ACCESS_PERMISSION",Uri.parse("package:"+getPackageName())));return;}catch(Exception ignored){}}requestPermissions(new String[]{Manifest.permission.READ_EXTERNAL_STORAGE,Manifest.permission.WRITE_EXTERNAL_STORAGE},100);}
 void openRuntime(){String p=runtime();if(p.isEmpty()){download();return;}Intent i=getPackageManager().getLaunchIntentForPackage(p);if(i==null){message("RetroArch","Open RetroArch from the TV app menu once.");return;}startActivity(i);}
 void download(){new AlertDialog.Builder(this).setTitle("Install official RetroArch").setMessage("Downloads the unmodified universal APK from the Libretro website. Android will ask you to allow installation. Cores are installed once inside RetroArch.").setPositiveButton("Download",(d,n)->{try{File f=new File(getExternalFilesDir(null),"retroarch.apk");if(f.exists()){install();return;}DownloadManager.Request r=new DownloadManager.Request(Uri.parse(APKURL));r.setTitle("RetroArch runtime");r.setNotificationVisibility(DownloadManager.Request.VISIBILITY_VISIBLE_NOTIFY_COMPLETED);r.setDestinationUri(Uri.fromFile(f));downloadId=((DownloadManager)getSystemService(DOWNLOAD_SERVICE)).enqueue(r);message("Downloading","Wait for the download to finish. The Android installer will open. If you leave this app, use Install RetroArch again when the download has completed.");}catch(Exception e){try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(APKURL)));}catch(Exception ignored){message("Download",APKURL);}}}).setNegativeButton("Cancel",null).show();}
 BroadcastReceiver downloadReceiver=new BroadcastReceiver(){public void onReceive(Context c,Intent i){long id=i.getLongExtra(DownloadManager.EXTRA_DOWNLOAD_ID,-2);if(id!=downloadId)return;DownloadManager dm=(DownloadManager)getSystemService(DOWNLOAD_SERVICE);try(Cursor q=dm.query(new DownloadManager.Query().setFilterById(id))){if(q!=null&&q.moveToFirst()&&q.getInt(q.getColumnIndexOrThrow(DownloadManager.COLUMN_STATUS))==DownloadManager.STATUS_SUCCESSFUL)install();else {new File(getExternalFilesDir(null),"retroarch.apk").delete();message("Download failed","Try Install RetroArch again. Check the TV network connection.");}}}};
 void install(){if(Build.VERSION.SDK_INT>=26&&!getPackageManager().canRequestPackageInstalls()){try{startActivity(new Intent(Settings.ACTION_MANAGE_UNKNOWN_APP_SOURCES,Uri.parse("package:"+getPackageName())));message("Allow installation","Allow Games Planet TV to install apps, return here and choose Install RetroArch again.");return;}catch(Exception e){message("Install permission","Allow unknown app installation for Games Planet TV in the TV settings.");return;}}try{Intent i=new Intent(Intent.ACTION_VIEW);i.setDataAndType(Uri.parse("content://com.gamesplanet.tv.install/retroarch.apk"),"application/vnd.android.package-archive");i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivity(i);}catch(Exception e){message("Installer",e.toString());}}
}
